apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: dev
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: Role
  name: "developer"
subjects:
  - apiGroup: "rbac.authorization.k8s.io"
    kind: User
    name: anisa
