apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: dev
  labels:
    app: nginx
    deploy: anisa
spec:
  template:
    metadata:
      name: myapp-pod-nginx
      labels:
        app: nginx
        type: front-end
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "nginx"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "size"
                operator: "In"
                values:
                   - "Large"
                   - "small"
      containers:
        - name: nginx-container-rep
          image: nginx:1.21
          resources:
            requests:
              cpu: "1m"
              memory: "10M"
            limits:
              cpu: "5m"
              memory: "100M"
  replicas: 20
  selector:                     # only contain these pods in replicaset
    matchLabels:
      type: front-end
