apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: dev
rules:
  - apiGroups:
    # core
     - ""
    resources:
      - "pods"
    verbs:
      - "list"
      - "get"
  - apiGroups:
     - "apps"
    resources:
     - "deployments"
    verbs:
     - "list"
     - "get"
     - "watch"
