apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-developer
rules:
  - apiGroups:
    # core
     - ""
    resources:
    ### when a namespaced resourse is called here, the user gets access to all the
    ### namespaces within the cluster
      - "pods"
    verbs:
      - "list"
      - "get"

  - apiGroups:
     - ""
    resources:
     - "nodes"
    verbs:
     - "list"
     - "create"
     - "get"
     - "watch"
