apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8080        # service port
  selector:
    type: front-end
