apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
  labels:
    type: front-end
    app: nginx
spec:
  type: NodePort  
  #type defaults to clusterIP
  ports:
    - targetPort: 80    # on the pod
      port: 8080        #on the service # defaults to targetPort
      nodePort: 30008   # defaults to a random value
  selector:
    type: front-end
