apiVersion: v1
kind: Pod
metadata:   # name of the pod, namespace, labels etc
  name: alp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: alpine-container
      image: alpine # default pulls out of dockerhub
      envFrom:
        - configMapRef:
            name: alpine-config
      command: 
        - sh 
        - -c
        - |
          ls /etc/
          echo $mohsen $ali
          sleep infinity
