apiVersion: v1
kind: Pod
metadata:   # name of the pod, namespace, labels etc
  name: multi-alp-pod
  labels:
    app: myapp

spec:
  volumes:
    - name: config
      configMap:
        name: alpine-config
  containers:
    - name: alpine-container-1
      image: alpine # default pulls out of dockerhub
      volumeMounts:
        - name: config
          mountPath: /mnt/config
      envFrom:
        - configMapRef:
            name: alpine-config
      command: 
        - sh 
        - -c
        - |
          ls /etc/
          echo $mohsen $ali
          sleep infinity
    - name: alpine-container-2
      image: alpine # default pulls out of dockerhub
      envFrom:
        - configMapRef:
            name: alpine-config
      command: 
        - sh 
        - -c
        - |
          ls /etc/
          echo $mohsen $ali
          sleep infinity
